### ISSUE TITLE
23andMe deletions

### ISSUE THREAD

**Issue by mathiasbynens** [genomejs/dna2json#11]
> 23andMe indicates deletions with `D`. Other groups use other standards. 

https://github.com/genomejs/gql/issues/4#issuecomment-94304062
https://github.com/genomejs/gql/issues/4#issuecomment-94307846

**Comment by contra** [comment]
Found a bunch more info on the 23andme API docs

https://api.23andme.com/docs/reference/#genotypes

```
For the user's profile, returns the base-pairs, like AA, for the given locations. The value can have Ds or Is for deletions and insertions (for example, DD or DI). It can be __ if the customer is not on a chip that calls that location, or hasn't yet unlocked their call since it corresponds to a sensitive report. It can be -- if the customer is on a chip that calls that location, but we could not determine it. To keep consistency with the /genomes endoint, which always returns two base pairs, hemizygous calls (such as on X-linked genes in males) will also return two base pairs. 
```

**Comment by mathiasbynens** [comment]
Note that some users cannot unlock this data at all:

> Your 23andMe kit was purchased on November 22, 2013 or later, granting you access to only ancestry information and uninterpreted raw data

**Comment by contra** [comment]
fixed in 1.1.2

**Comment by zhaofengli** [comment]
No call (`--` in raw data) isn't the same as deletion. SNP-JSON perhaps should use `??` to indicate no-calls.

**Comment by contra** [comment]
@zhaofengli That makes sense, want to send a PR? I think https://github.com/genomejs/gql might need some tweaks for that.

Have you seen any docs on the 23andme csv format?
