### ISSUE TITLE
SNP-JSON format

### ISSUE THREAD

**Issue by axdg** [genomejs/dna2json#14]
From what I can see in the [demo genomes](https://github.com/genomejs/demo-genomes), all vendors provide as chromosomal location, is there any reason why this isn't included a a property in the SNP-JSON.

**Comment by contra** [comment]
@axdg File size mostly - some of the information isn't really that important to have in the file. AFAIK the chromosomal location can be looked up in the reference genome.

**Comment by contra** [comment]
included now afaik
