### ISSUE TITLE
Using JSONStream

### ISSUE THREAD

**Issue by pvjones** [genomejs/dna2json#16]
Thanks for the incredible work on this library. Also, thanks for the great usage documentation. I'm new to coding, and was able to quickly get this working in both CLI and a node app. 

Quick question. I saw one example on a blog where someone had implemented dna2json with JSONStream, like so:

var dna = require('dna2json');
var JSONStream = require('JSONStream');
var fs = require('fs');
 
fs.createReadStream("./data/23andme-male.txt")
  .pipe(dna.createParser())
  .pipe(JSONStream.stringify())
  .pipe(fs.createWriteStream("./data/23andme-male.json"));

Is this necessary? What are the pros/cons?

**Comment by contra** [comment]
That was with the old API, no longer necessary. All of the streaming stuff was removed a while ago to simplify the API.

What blog post was it? Might be worth emailing them to update.

**Comment by pvjones** [comment]
Thanks for the help! People like yourself make me excited for future involvement with the developer community. 

The blog post is right here: http://thejackalofjavascript.com/dna-analysis-node-js/

If it would be helpful, I'd be happy to attempt contact and point out that the library has been updated.

**Comment by contra** [comment]
@pvjones Yeah if you wouldn't mind that would be cool, glad that some people are using this!
