### ISSUE TITLE
Orientation issues

### ISSUE THREAD

**Issue by pvjones** [genomejs/dna2json#17]
I'm still learning and re-learning all this sequencing stuff, so this may or may not be an issue. Has orientation been considered for the three vendors listed in the readme? I've read that 23andMe reports genotype information based on the plus strand of GRCh37, while some other companies use the minus strand (I'm not sure what FamilyTree and AncestryDNA use). If that's the case, this would need to be accounted for, since use of the opposite strand would require that all A/T, and all G/C nucleobases be 'flipped'  for queries to be accurate. (This is discussed more [on SNPedia](http://www.snpedia.com/index.php/Orientation).) 

Is this already known and accounted for?  Thanks!

**Comment by contra** [comment]
I think this should be accounted for, do you want to test and confirm? There are a few sample exports from different providers in this repo.

**Comment by pvjones** [comment]
I've done some more reading and testing, and I believe that this doesn't really need to be accounted for in dna2json. It seems that 23andMe uses alternative notation for the rsid when they report values for the plus strand (for example, i4000436 instead of rs121907957 for a common Tay-Sachs mutation). dna2json should handle this just fine. If someone is writing a gql query, however, they would need to account for this difference. That should be pretty straightforward.
