### ISSUE TITLE
AncestryDNA only returns one allele per rs#?

### ISSUE THREAD

**Issue by pvjones** [genomejs/dna2json#18]
Please excuse my ignorance, if this question is ill-informed.

I have a sample TXT file from AncestryDNA. Unlike the other two vendors, it looks like they list the two alleles for each rs# in separate columns. As a result, my JSON file only contains one allele per rs#. The result looks like this:

`"rs4477212": {
    "chromosome": 1,
    "genotype": "T"
  },
  "rs3131972": {
    "chromosome": 1,
    "genotype": "A"
  },
  "rs12562034": {
    "chromosome": 1,
    "genotype": "G"
  }`

Is this an error on my part, or a limitation with AncestryDNA's TXT file formatting?

Thanks!

**Comment by contra** [comment]
Might be a mishap on the part of our parser, I'll mark it as a bug and look at it when I have a minute.

Do you have an AncestryDNA file you could share? They might have modified the formatting.

**Comment by pvjones** [comment]
Thanks for the reply! Yes, these are the results I obtained using the sample genome [here](https://github.com/genomejs/demo-genomes/blob/master/ancestry-female.txt).

**Comment by pvjones** [comment]
It could be a completely incorrect way to approach this, but I submitted a pull request for the Ancestry.js parser that seems to fix the issue.

**Comment by robertkowalski** [comment]
hmm... with

c055f5b799f0de875e1285f84b7ec934f918e957
and
ceff1b6e720765f05a67e5775de785eba45520d4

throw an error as soon as you have a 0 0

what does the 0 mean btw?

**Comment by contra** [comment]
Yeah, that first commit I figured would have an issue.

I'm not sure what the 0 in ancestry means - I've never worked with anything from ancestry other than their demo file.

**Comment by contra** [comment]
Our demo file might be old, it looks like they changed their format recently

**Comment by robertkowalski** [comment]
got that from their docs:

The possible observations are A for adenine, C for cytosine, G for guanine,
T for thymine, I for insertion’ and ‘D for deletion, or 0 for missing data.

**Comment by pvjones** [comment]
You can find publicly available genomes [here](https://my.pgp-hms.org/public_genetic_data?utf8=%E2%9C%93&data_type=other). Some of them quite recent. Currently second-from-the-top is an AncestryDNA file uploaded on Jan 7, 2017. I just opened it up and there are indeed plenty of 0 values. So is that a new thing for AncestryDNA?

**Comment by robertkowalski** [comment]
good question, no clue

**Comment by contra** [comment]
Cool, so we should skip zeros in dna2json if it means missing data.

**Comment by contra** [comment]
Published as 1.0.3
