### ISSUE TITLE
Genes for Good

### ISSUE THREAD

**Issue by pvjones** [genomejs/dna2json#21]
Hey, do you have any interest in adding a parser for Genes for Good? It's a [group at University of Michigan](https://genesforgood.sph.umich.edu/) that offers free genotyping. 

They provide users with text files formatted in the same manner as 23andMe. Because of that, it should be pretty straightforward to create a new parser based on the one already written for 23andMe. If you are interested, I could test it out with some Genes for Good TXT files I have from a friend.

**Comment by contra** [comment]
@pvjones Yeah that would be cool, shoot me a PR and I'll merge that in.

Also have a ticket open for SAM/BAM files https://github.com/genomejs/dna2json/issues/6

**Comment by pvjones** [comment]
Cool. I'm testing it out right now. One potential problem is that Genes for Good allows users to download various file formats. Only one of them works on my machine. The other formats offer "imputed" data and are much, much longer, with file-sizes around 200 MB. When I try to run these, I exceed the V8 memory limit and Node crashes. You could prevent this by disallowing any of the longer imputed file types, by adding a condition in the return for 'matches' checking indexOf('unphased').

**Comment by contra** [comment]
@pvjones I can fix the memory issue, one sec

**Comment by contra** [comment]
published
