### ISSUE TITLE
Extremely Long Parse Time

### ISSUE THREAD

**Issue by johnstonian** [genomejs/dna2json#3]
I tried to parse my genome from the text file downloaded from 23andMe. It appears to get stuck while parsing the SNPs. I let the script run for 3 hours and it appeared to be stuck on "Parsed 960613 SNPs". 

Is there an error log or debug feature that I can use to find out what is happening? The example listed in the readme says "This will take awhile..." What is the average time it takes to parse a genome?

Some other information that may be useful:
genome file downloaded from 23andMe is 24 MB
After stopping the data2json process after 3 hours, the json file was 34 MB.

Thanks for any help you can provide

**Comment by contra** [comment]
just rewrote the whole thing, should be much faster now

**Comment by johnstonian** [comment]
+1 !!!
